apiVersion: apps/v1
kind: Deployment
metadata:
  name: painchoc-blog
  namespace: painchoc
  labels:
    app: painchoc-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: painchoc-blog
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: painchoc-blog
    spec:
      containers:
      - name: painchoc
        image: eu.gcr.io/khaly-221308/demo-contour
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
        env:
        - name: VERSION
          value: "Blog"
        - name: TEAM
          value: "Painchoc"
        - name: LABEL
          value: "Team"
        - name: ROUTING
          value: "false"
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: painchoc-blog
  namespace: painchoc
  labels:
    app: painchoc-blog
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: painchoc-blog
