apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: flamant-food
  namespace: flamant-food
  labels:
    app: main-flamant-food
spec:
  virtualhost:
    fqdn: flamant.food
    tls:
      secretName: flamant-tls
  routes:
  - match: /
    services:
    - name: flamant-food
      port: 80
  - match: /painchoc
    delegate:
      name: painchoc
      namespace: painchoc
  - match: /chocolatine
    delegate:
      name: chocolatine
      namespace: chocolatine
